# Generated by Django 3.2.22 on 2023-10-08 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Идентификатор записи')),
                ('date', models.DateField(verbose_name='Дата')),
                ('amount', models.FloatField(verbose_name='Сумма на указанную дату')),
                ('real_amount', models.FloatField(null=True, verbose_name='Реальная сумма на указанную дату')),
                ('comment', models.CharField(max_length=100, null=True, verbose_name='Комментарий')),
            ],
        ),
        migrations.CreateModel(
            name='DateExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DateProfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Идентификатор расхода')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование расхода')),
                ('start_date', models.DateField(verbose_name='Дата расхода')),
                ('amount', models.FloatField(verbose_name='Сумма расхода')),
                ('custom_replay_days', models.IntegerField(null=True, verbose_name='Количество дней повторения для кастомного повтора')),
                ('finish_date', models.DateField(null=True, verbose_name='Дата окончания повтора')),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Идентификатор модели')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование модели')),
                ('start_date', models.DateField(verbose_name='Дата начала моделирования')),
                ('finish_date', models.DateField(verbose_name='Дата окончания моделирования')),
                ('start_amount', models.FloatField(verbose_name='Сумма счета на начало моделирования')),
            ],
        ),
        migrations.CreateModel(
            name='ReplayType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Идентификатор повтора')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование повтора')),
                ('days', models.IntegerField(null=True, verbose_name='Количество дней повторения')),
                ('month', models.IntegerField(null=True, verbose_name='Количество месяцев повторения')),
                ('years', models.IntegerField(null=True, verbose_name='Количество лет повторения')),
            ],
        ),
        migrations.CreateModel(
            name='Profit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Идентификатор дохода')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование дохода')),
                ('start_date', models.DateField(verbose_name='Дата дохода')),
                ('amount', models.FloatField(verbose_name='Сумма дохода')),
                ('custom_replay_days', models.IntegerField(null=True, verbose_name='Количество дней повторения для кастомного повтора')),
                ('finish_date', models.DateField(null=True, verbose_name='Дата окончания повтора')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.model')),
                ('replay_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.replaytype')),
            ],
        ),
    ]
