# Generated by Django 3.2.22 on 2023-10-08 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expense',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.model'),
        ),
        migrations.AddField(
            model_name='expense',
            name='replay_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.replaytype'),
        ),
        migrations.AddField(
            model_name='dateprofit',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.date'),
        ),
        migrations.AddField(
            model_name='dateprofit',
            name='profit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.profit'),
        ),
        migrations.AddField(
            model_name='dateexpense',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.date'),
        ),
        migrations.AddField(
            model_name='dateexpense',
            name='expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.expense'),
        ),
        migrations.AddField(
            model_name='date',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.model'),
        ),
    ]
