# Generated by Django 3.2.22 on 2023-10-12 16:08

from django.db import migrations, models

def replay_types(apps, schema_editor):
    # Типы - наш перечень, который будет вставлен в БД
    ids = [1, 2, 3, 4, 5]
    names = ["Каждый день", "Каждый месяц", "Каждый год", "Пользовательский", "Без повтора"]
    days = [1, 0, 0, 0, 0]
    months = [0, 1, 0, 0, 0]
    years = [0, 0, 1, 0, 0]

    # Попросим Django вытащить модель - класс ClientTypes из аппликейшена user_profile
    ReplayType = apps.get_model("finance", "ReplayType")

    # Теперь в цикле создаём экземпляры класса с указанными параметрами и сохраняем их
    for i in range(len(ids)):
        repl_type = ReplayType(id = ids[i], name = names[i], days = days[i], months = months[i], years = years[i])
        repl_type.save()


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_rename_month_replaytype_months'),
    ]

    operations = [
        migrations.RunPython(replay_types),
    ]
